name: Lint and Fix Python Code

on:
  pull_request:
    branches:
      - main  # Trigger on pull requests to `main`

jobs:
  lint-and-fix:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pylint autopep8

      # Step 4: Run pylint on specific files
      - name: Run pylint on specified files
        id: pylint
        run: |
          pylint_output=$(pylint $(git ls-files '*.py' | grep -vE '(^tests/|^docs/)') --output-format=text) || true
          echo "$pylint_output"
          echo "::set-output name=pylint_output::$pylint_output"

      # Step 5: Apply autopep8 fixes to the files
      - name: Apply autopep8 fixes
        run: |
          autopep8 --in-place --aggressive --aggressive $(git ls-files '*.py' | grep -vE '(^tests/|^docs/)')

      # Step 6: Request changes using suggest-changes action
      - name: Request changes from autopep8 fixes
        uses: parkerbxyz/suggest-changes@v1
        with:
          comment: 'Please commit the suggested changes from pylint and autopep8.'
          event: 'REQUEST_CHANGES'
