name: OpenSSF Scorecard
on:
  workflow_dispatch:
  schedule:
    - cron: '30 1 * * 6'
  push:
    branches: [ "main" ]

permissions: read-all

jobs:
  analysis:
    name: Scorecard analysis
    runs-on: ubuntu-latest
    permissions:
      security-events: write
      id-token: write
    steps:
      - name: "Checkout code"
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: "Set up Homebrew"
        uses: Homebrew/actions/setup-homebrew@main

      - name: "Install Scorecard via Homebrew"
        run: |
          brew install scorecard

      - name: "Run Scorecard CLI"
        env:
          GITHUB_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          scorecard --repo=://github.com{{ github.repository }} \
                    --format=sarif \
                    --output=results.sarif \
                    --publish=true

      - name: "Upload results to Security Tab"
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: results.sarif
