name: PR Check

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  label-pr:
    runs-on: ubuntu-latest
    
    permissions:
      contents: read
      pull-requests: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Conditional Labeling
        if: ${{ github.actor != 'github/sharktide' }}
        uses: actions/labeler@v4
        with:
          configuration-path: .github/labeler.yml
          github-token: ${{ secrets.GITHUB_TOKEN }}
