name: PR Check

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  pr-check:
    runs-on: ubuntu-latest

    steps:
      - name: Set up environment
        run: |
          echo "GITHUB_ACTOR=${{ github.actor }}" >> $GITHUB_ENV
          echo "GITHUB_REPO=${{ github.repository }}" >> $GITHUB_ENV
          echo "BASE_REF=${{ github.base_ref }}" >> $GITHUB_ENV
          echo "HEAD_REF=${{ github.head_ref }}" >> $GITHUB_ENV

      - name: Fetch pyproject.toml from base branch
        run: |
          curl -s "https://raw.githubusercontent.com/${GITHUB_REPO}/${BASE_REF}/pyproject.toml" -o base_pyproject.toml || echo "Base file not found"

      - name: Fetch pyproject.toml from head branch
        run: |
          curl -s "https://raw.githubusercontent.com/${GITHUB_REPO}/refs/heads/${HEAD_REF}/pyproject.toml" -o head_pyproject.toml || echo "Head file not found"

      - name: Compare pyproject.toml files
        run: |
          if [[ "${GITHUB_ACTOR}" != "github/sharktide" ]]; then
            echo "User is not sharktide"
            if ! cmp -s base_pyproject.toml head_pyproject.toml; then
              echo "pyproject.toml has been changed, and the user is not github/sharktide."
              exit 1
            fi
          fi
          echo "Check passed."
