name: PR Check

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  pr-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run PR validation
        run: python .github/scripts/check_conditions.py
        env:
          GITHUB_ACTOR: ${{ github.actor }}
          GITHUB_BASE_REF: ${{ github.base_ref }}
          GITHUB_HEAD_REF: ${{ github.head_ref }}
