name: Pull Request

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
    paths-ignore:
      - 'docs/**'
      - '.github/**'
      - '.gitattributes'
      - '.gitignore'
      - 'README.md'

permissions:
  issues: write
  pull-requests: write

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5

      - name: Install cibuildwheel
        run: python -m pip install --upgrade pip setuptools wheel toml build

      - name: Build wheels
        run: python -m build --sdist

      - uses: actions/upload-artifact@v4
        with:
          name: sdist
          path: dist/*
      
      - name: Comment on PR with artifact link
        if: github.event_name == 'pull_request'
        uses: peter-evans/create-or-update-comment@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            ### We successfully built a source distribution!
            You can [download it from the workflow run](https://github.com/sharktide/actions/runs/${{ github.run_id }})
            This will be avalible for 90 days.
