name: Lint and Comment on PR

on:
  pull_request:
    branches:
      - main  # Adjust based on your default branch
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pylint

      - name: Run pylint
        id: pylint
        run: |
          pylint_output=$(pylint $(find . -type f -name "*.py" ! -path "./tests/*" ! -path "./docs/*") --output-format=text)
          echo "$pylint_output"
          echo "::set-output name=pylint_output::$pylint_output"

      - name: Comment on PR with Linter Results
        if: github.event_name == 'pull_request'
        run: |
          if [[ -n "${{ steps.pylint.outputs.pylint_output }}" ]]; then
            curl -H "Authorization: token ${{ secrets.GH_PAT }}" \
                 -X POST \
                 -d '{"body": "## Linter Report:\n\n'$(echo ${{ steps.pylint.outputs.pylint_output }} | sed 's/\n/\\n/g')'\n\nYou can apply the fixes by clicking the button below:\n\n[Apply Linter Fixes](https://github.com/${{ github.repository }}/actions/workflows/fix-linter.yml/dispatches)"}' \
                 https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.pull_request.number }}/comments
          else
            echo "No linting issues found."
          fi
